gdb/loongarch-linux-tdep.h
=> gdb: redefine gpr/fpr num

gas/config/loongarch-parse.y, gas/config/tc-loongarch.c, gdb/loongarch-tdep.c, opcodes/loongarch-dis.c
gas/config/loongarch-parse.y
opcodes/loongarch-dis.c
=> binutils: delete compile diagnostics

include/elf/common.h
=> gdb: change code comment.

bfd/elfxx-loongarch.c, include/elf/loongarch.h, ld/emultempl/loongarchelf.em
bfd/elfxx-loongarch.c:
change "loong_reloc_map" into "larch_reloc_map"
include/elf/loongarch.h:
change "_ELF_LOONG_H" into "_ELF_LOONGARCH_H"
ld/emultempl/loongarchelf.em:
change "loong_elf_before_allocation" into "larch_elf_before_allocation"
change "loong_create_output_section_statements" into "larch_create_output_section_statements"
=> change name "loong_" into "larch_", "LOONG_" into "LOONGARCH_".

gas/config/tc-loongarch.c
=> Add some annotation of instruction opcodes.

bfd/cpu-loongarch.c, bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, bfd/elfxx-loongarch.h, gas/config/loongarch-lex-wrapper.c, gas/config/loongarch-lex.l, gas/config/loongarch-parse.y, gas/config/tc-loongarch.c, gas/config/tc-loongarch.h, gdb/arch/loongarch-linux-nat.h, gdb/arch/loongarch.c, gdb/loongarch-linux-nat.c, gdb/loongarch-linux-tdep.c, gdb/loongarch-linux-tdep.h, gdb/loongarch-tdep.c, gdb/loongarch-tdep.h, gdb/nat/loongarch-linux-watch.c, gdb/nat/loongarch-linux-watch.h, gdbserver/linux-loongarch-low.cc, include/elf/loongarch.h, include/opcode/loongarch.h, ld/emultempl/loongarchelf.em, opcodes/loongarch-coder.c, opcodes/loongarch-dis.c, opcodes/loongarch-opc.c
bfd/cpu-loongarch.c
bfd/elfxx-loongarch.h
gas/config/loongarch-lex-wrapper.c
gas/config/loongarch-lex.l
gas/config/loongarch-parse.y
gas/config/tc-loongarch.h
gdb/arch/loongarch-linux-nat.h
gdb/arch/loongarch.c
gdb/loongarch-linux-nat.c
gdb/loongarch-linux-tdep.c
gdb/loongarch-linux-tdep.h
gdb/loongarch-tdep.c
gdb/loongarch-tdep.h
gdb/nat/loongarch-linux-watch.c
gdb/nat/loongarch-linux-watch.h
gdbserver/linux-loongarch-low.cc
include/elf/loongarch.h
include/opcode/loongarch.h
ld/emultempl/loongarchelf.em
opcodes/loongarch-coder.c
opcodes/loongarch-dis.c
opcodes/loongarch-opc.c
=> binutils: change format by check_GNU_style.sh

bfd/elfxx-loongarch.c, gdb/nat/loongarch-linux-watch.c, gdb/nat/loongarch-linux-watch.h, include/elf/loongarch.h
gdb/nat/loongarch-linux-watch.c
gdb/nat/loongarch-linux-watch.h
include/elf/loongarch.h
=> binutils: Add Base on desc.

bfd/elfnn-loongarch.c
=> bfd: delete jr insn

gdb/loongarch-tdep.c
=> gdb: delete insns

gas/doc/as.texi
=> gas/doc: change LoongArch seq.

gas/config/tc-loongarch.c, gas/testsuite/gas/all/gas.exp
=> gas: fix bug. gas/all/gas.exp

bfd/elfnn-loongarch.c, binutils/readelf.c, gas/config/tc-loongarch.c, gdb/arch/loongarch.h
binutils/readelf.c
gdb/arch/loongarch.h
=> change code format.

gas/config/tc-loongarch.c, gas/config/tc-loongarch.h
=> gas: change format && add nop binary code

gas/config/tc-loongarch.c, gas/testsuite/gas/elf/elf.exp
=> gas: fix bugs. make check FAIL: macros dot FAIL: macros purge

gdb/arch/loongarch-linux-nat.c, gdb/arch/loongarch-linux-nat.h, gdb/arch/loongarch.c, gdb/arch/loongarch.h, gdb/loongarch-linux-tdep.c, gdb/loongarch-tdep.c
Reverts loongson/binutils-gdb#61
=> Revert "use struct loongarch_gdbarch_features"

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c
=> bfd: Redefine howto table.

gas/config/tc-loongarch.c, opcodes/loongarch-coder.c
=> gas/opcode: fix memory leaks.

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c
=> bfd: fix bugs. merged from redefine howto table.

bfd/elfxx-loongarch.c
=> Modify relocation type in howto_table: R_LARCH_NONE.

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, bfd/elfxx-loongarch.h
This fix binutils test strip-13.
=> Handle reloc type overflow.

bfd/elfnn-loongarch.c
=> ld: check contents offset

gas/config/tc-loongarch.c, include/opcode/loongarch.h, opcodes/loongarch-dis.c, opcodes/loongarch-opc.c
include/opcode/loongarch.h
opcodes/loongarch-dis.c
opcodes/loongarch-opc.c
=> binutils: Add new float isa

ld/Makefile.am, ld/Makefile.in, ld/emulparams/elf32loongarch-defs.sh, ld/emulparams/elf32loongarch.sh, ld/po/BLD-POTFILES.in
ld/Makefile.am
ld/Makefile.in
ld/emulparams/elf32loongarch-defs.sh
ld/emulparams/elf32loongarch.sh
ld/po/BLD-POTFILES.in
=> ld: Add new elf32

bfd/elfnn-loongarch.c
=> ld: Fix bugs. gdb print TLS vars address error.

gdb/loongarch-tdep.c
* print $f0, print $fv0 *
gdb/loongarch-tdep.c
=> gdb: Add float register names.

opcodes/loongarch-coder.c
=> gas: Fix warning in ubsan.

ld/testsuite/ld-elf/eh5.d, ld/testsuite/ld-elf/pr21884.d, ld/testsuite/ld-elf/pr26936.d
ld/testsuite/ld-elf/eh5.d
ld/testsuite/ld-elf/pr21884.d
ld/testsuite/ld-elf/pr26936.d
* of expected passes		1358
* of unexpected failures	19
* of unexpected successes	1
* of expected failures		7
* of untested testcases		1
* of unsupported tests		141
=> ld: Fix make check fail.

binutils/objcopy.c
objcopy -I binary -O elf64-loongarch --alt-elf-eflags=0x3 bin  elf
binutils/objcopy.c
=> binutils: Add option in objcopy

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, bfd/elfxx-loongarch.h, gas/config/tc-loongarch.c
bfd/elfxx-loongarch.h
=== gas Summary ===
of expected passes	256
of expected failures	2
of unsupported tests	3
=== binutils Summary ===
of expected passes	233
of unsupported tests	6
=== ld Summary ===
of expected passes	1405
of unexpected failures	11
of unexpected successes	1
of expected failures	10
of untested testcases	1
of unsupported tests	140
=> gas: fix tls bugs. gas/ld: fix reloc insn fill.

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, bfd/elfxx-loongarch.h, gas/config/tc-loongarch.c
bfd/elfxx-loongarch.h
=== gas Summary ===
of expected passes		256
of expected failures		2
of unsupported tests		3
=== binutils Summary ===
of expected passes		233
of unsupported tests		6
=== ld Summary ===
of expected passes		1405
of unexpected failures	11
of unexpected successes	1
of expected failures		10
of untested testcases		1
of unsupported tests		140
=> gas/ld: fix reloc func.

bfd/elfxx-loongarch.c
=> R_LARCH_SOP_POP_32_S_5_20 HOWTO TABLE dst_mask

bfd/elfnn-loongarch.c, gdb/features/loongarch/base32.xml, gdb/features/loongarch/base64.c, gdb/features/loongarch/base64.xml, gdb/loongarch-linux-tdep.c, gdb/loongarch-tdep.c, gdb/loongarch-tdep.h
Reverts loongson/binutils-gdb#127
=> Revert "Upstream v3.1 fix1"

bfd/version.h
This reverts commit 2dc60c77108cad22c270cec3f88d01fd20716a35.
=> Revert "Automatic date update in version.in"

gas/config/tc-loongarch.c, gas/config/tc-loongarch.h, include/opcode/loongarch.h, ld/testsuite/ld-loongarch-elf/macro_op.s, ld/testsuite/ld-loongarch-elf/macro_op_32.d, ld/testsuite/ld-loongarch-elf/macro_op_32.s, opcodes/loongarch-opc.c
Macro insn expand 64 bit insns in as-32.
=> LoongArch: gas: Fix check bug.

bfd/elfnn-loongarch.c
Reverts loongson/binutils-gdb#145
=> Revert "Test tmp binutils nopic format code 2"

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, gas/config/tc-loongarch.c
Reverts loongson/binutils-gdb#143
=> Revert "LoongArch: Format code."

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, gas/config/loongarch-lex.h, gas/config/loongarch-parse.y, gas/config/tc-loongarch.c, gas/testsuite/gas/loongarch/macro_op_32.d
Fix some dst_mask. (pcaddu12i,bl)
=== gas Summary ===
of expected passes            265
of unsupported tests          7
=== binutils Summary ===
of expected passes            236
of unsupported tests          6
=== ld Summary ===
of expected passes            1441
of unexpected failures        2
of expected failures          10
of untested testcases         1
of unsupported tests          154
=> LoongArch: Write addend to insn in as.

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c, gas/config/loongarch-lex.h, gas/config/loongarch-parse.y, gas/config/tc-loongarch.c, gas/testsuite/gas/loongarch/macro_op_32.d
Reverts loongson/binutils-gdb#154
=> Revert "LoongArch: Write addend to insn in as."

bfd/elfnn-loongarch.c, gas/config/tc-loongarch.c, ld/testsuite/ld-loongarch-elf/attr-ifunc-4.c, ld/testsuite/ld-loongarch-elf/attr-ifunc-4.out, ld/testsuite/ld-loongarch-elf/ifunc.exp, ld/testsuite/ld-loongarch-elf/pic.exp
gas md_apply_fix must output ifunc symbol reloc
create diff ifunc relocate sections for PIC object, dynamic executable and static executable
add static ifunc test
=> gas md_apply_fix for ifunc symbol

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.c
=> Fix tls bug while use got.

bfd/elfnn-loongarch.c
TLS static link error.
TLS IE GD relocate_section process togother.
TLS old reloc process update to new style.
=> LoongArch: fix TLS bugs

bfd/elfnn-loongarch.c
This reverts commit 728c39008aa0c6d71d3fb7251d12b9ab15ac99a8.
=> Revert "LoongArch: Add assert while ld.d + addend in 2k page edge."

bfd/elfnn-loongarch.c, bfd/elfxx-loongarch.h, gas/config/loongarch-parse.y, gas/config/tc-loongarch.c, ld/emultempl/loongarchelf.em
=> Upstream v5.1 test relax
